const GAME_LEVELS = [
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                   xxx          ",
    "                                                    xx      xx    xx!xx         ",
    "                                     o o      xx                  x!!!x         ",
    "                                                                  xx!xx         ",
    "                                    xxxxx                          xvx          ",
    "                                                                            xx  ",
    "  xx                                       o o                               x  ",
    "  x                       o                                                  x  ",
    "  x                                       xxxxx                            o x  ",
    "  x           xxxx        o                                                  x  ",
    "  x  @        x  x                                                xxxxx      x  ",
    "  xxxxxxxxxxxxx  xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxx  ",
    "                                x   x                 x     x                   ",
    "                                x!!!x                 x!!!!!x                   ",
    "                                x!!!x                 x!!!!!x                   ",
    "                                xxxxx                 xxxxxxx                   ",
    "                                                                                ",
    "                                                                                ",
];